### PR TITLE
Add revert category extractionand exclude `ghfirst` reverts from stats

### PR DESCRIPTION
**Pull request by izaitsevfb**
Adds revert category extraction from GitHub comments and excludes `ghfirst` reverts from precision/recall metrics.

### 1. Added Revert Category Extraction
- New method `extract_revert_categories_batch()` in `autorevert_checker.py`
- Extracts categories (`nosignal`, `ignoredsignal`, `landrace`, `weird`, `ghfirst`) from GitHub issue comments
- Single batch query for performance

### 2. Enhanced `get_commits_reverted_with_info()`
- Now includes category information for each revert
- Uses batch extraction for all reverts at once

### 3. Updated Metrics Calculation
- Excludes `ghfirst` reverts from recall calculation
- Shows category breakdown in summary statistics
- Per-workflow precision now shows both total and non-ghfirst metrics

### 4. Fixed Pattern Detection Bug
- Fixed `AttributeError: 'NoneType' object has no attribute 'head_sha'`
- Created proper mapping between failures and their newer commits

<details>
<summary>Bug Fix Details</summary>

**Problem**: `newer_commit_same_job` was used outside its loop scope
**Solution**: Created `failure_to_newer_commit` dict to track mappings
```python
# Map each failure to its newer commit
failure_to_newer_commit = {}
for (rule, job) in suspected_failures:
    newer_commit_same_job, newer_same_jobs = self._find_last_commit_with_job(...)
    if newer_commit_same_job and any(...):
        failure_to_newer_commit[(rule, job)] = newer_commit_same_job

# Use mapping in pattern creation
for (failure_rule, job_name), newer_commit in failure_to_newer_commit.items():
    patterns.append({
        "newer_commits": [newer_commit.head_sha, suspected_commit1.head_sha],
        ...
    })
```
</details>

## Example Output

```
 python -m pytorch_auto_revert autorevert-checker Lint trunk pull inductor linux-binary-manywheel  --hours 720 --verbose

==================================================
SUMMARY STATISTICS
==================================================
Workflow(s): Lint, trunk, pull, inductor, linux-binary-manywheel
Timeframe: 720 hours
Commits checked: 6741
Auto revert patterns detected: 419
Actual reverts inside auto revert patterns detected (precision): 50 (11.9%)
Total revert commits in period: 121

Revert categories:
  nosignal: 46 (38.0%)
  ghfirst: 28 (23.1%)
  uncategorized: 21 (17.4%)
  ignoredsignal: 16 (13.2%)
  weird: 9 (7.4%)
  landrace: 1 (0.8%)

Total reverts excluding ghfirst: 93
Reverts (excluding ghfirst) that dont match any auto revert pattern detected (recall): 50 (53.8%)
Per workflow precision:
  Lint: 6 reverts out of 17 patterns (35.3%) [excluding ghfirst: 6 (35.3%)]
  trunk: 2 reverts out of 14 patterns (14.3%) [excluding ghfirst: 2 (14.3%)]
  pull: 40 reverts out of 354 patterns (11.3%) [excluding ghfirst: 33 (9.3%)]
  inductor: 2 reverts out of 31 patterns (6.5%) [excluding ghfirst: 2 (6.5%)]
  linux-binary-manywheel: 0 reverts out of 3 patterns (0.0%) [excluding ghfirst: 0 (0.0%)]

Reverted patterns:
  - Python RuntimeError: e1aee866 (ignoredsignal)
  - GitHub workflows weren't regenerated: 3b6569b1 (ignoredsignal)
  - GitHub workflows weren't regenerated: bbbced94 (landrace)
  - Python RuntimeError: 060838c2 (nosignal)
  - Lintrunner failure: 1a55fb0e (weird)
  - Lintrunner failure: 3239da0c (nosignal)
  - MSVC compiler error: eab45643 (ignoredsignal)
  - Bad response status code: ea7b2330 (uncategorized)
  - gtest failure: 347ace4c (nosignal)
  - pytest failure: 216bd609 (nosignal)
  - pytest failure: 84c588e5 (ignoredsignal)
  - GHA error: 863327ae (ignoredsignal)
  - GHA error: eb9efb37 (ghfirst)
  - GHA error: 9c39bc24 (ignoredsignal)
  - Python Test File RuntimeError: 6de41ce0 (uncategorized)
  - Fallback for other test failure rules: 3f920f3d (nosignal)
  - pytest failure: f179b719 (ghfirst)
  - pytest failure: 92409b6c (uncategorized)
  - pytest failure: d1b4e0fa (nosignal)
  - pytest failure: 099d0d61 (uncategorized)
  - pytest failure: c79c7bbe (nosignal)
  - pytest failure: c95f7fa8 (nosignal)
  - pytest failure: 08dae945 (weird)
  - pytest failure: fb75dea2 (uncategorized)
  - pytest failure: 9de23d0c (uncategorized)
  - pytest failure: 830a335a (ghfirst)
  - pytest failure: 6d3a4356 (ignoredsignal)
  - pytest failure: a6a3a441 (nosignal)
  - Python Test timeout (KeyboardInterrupt): 8142a028 (nosignal)
  - pr_time_benchmarks regression: 2b9d638e (weird)
  - pytest failure: dc5e8f79 (nosignal)
  - pytest failure: 5264f8cd (weird)
  - pytest failure: 8823138e (nosignal)
  - pytest failure: f154f9b3 (ignoredsignal)
  - pr_time_benchmarks regression: b07725a9 (ghfirst)
  - pr_time_benchmarks regression: d4d0ede6 (ignoredsignal)
  - Build error: 2596e3d0 (nosignal)
  - pytest failure: c1f531f0 (ghfirst)
  - GHA error: c6b4f986 (nosignal)
  - GHA error: 529e0357 (nosignal)
  - GHA error: e694280d (ghfirst)
  - GHA error: e1180c72 (weird)
  - GHA error: 7dcc77e4 (nosignal)
  - GHA error: a3098a74 (ignoredsignal)
  - GHA error: a14f427d (nosignal)
  - GHA error: bee9c70c (nosignal)
  - GHA error: 409c396a (ghfirst)
  - GHA error: 67fb9b7c (nosignal)
  - GHA error: 1b50c125 (nosignal)
  - pytest failure: 196c95d4 (nosignal)
```

### CODE REVIEW

File: aws/lambda/pytorch-auto-revert/.env.example [hunk 1]
```diff
@@ -1,7 +1,7 @@
 # ClickHouse Configuration
 CLICKHOUSE_HOST=your_clickhouse_host
 CLICKHOUSE_PORT=9000
-CLICKHOUSE_USER=default
+CLICKHOUSE_USERNAME=default
```
Comment (izaitsevfb) [inline aws/lambda/pytorch-auto-revert/.env.example:4]: ideally we'd want to change it back to `CLICKHOUSE_USER` (and refactor all cli params accordingly), as that's what we use in other project / places.
